// Generated by prost_build from protobufs/sim/world.proto (see ../build.rs).
// The include path matches prost's default OUT_DIR output.
pub mod world {
    include!(concat!(env!("OUT_DIR"), "/norma_sim.world.v1.rs"));
}

pub use world::*;
